# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4480eb26122969eb610a40280556517ef115f3e473d31d764003ece257c379e5bdfdf534bb6422ad78bfc9ffc1b1458edc7f4361b29c5417c8357434afe0ee0

test:
  secret_key_base: 5f3fb408b9472004bf330bb60e2c23736d5c352bfa87b0dccc80796bf4281c36085e11ce5fe8289bb73478a8feb2e892ad8ae1bab7ba28f9e802199f4a4d2272

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
